default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: postgres
      password: password

development:
  <<: *default
  database: hosting_app_development

test:
  <<: *default
  database: hosting_app_test

production:
  <<: *default
  database: hosting_app_production