# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55ca429a0255a1f203ce1ab0963626eb0e9c9a4885d4997e205687e3f32c200e5c9cb871f3206984a1724e31d6257b63ea5a642af7c24fe175ea10fb06195e5

test:
  secret_key_base: 26a2d96e3dae6e9de761aafb98d3246e877164d78d1ef5a35f67e165cdf2977e030122ff8552235cff1352355503c91948f973b157f7c1e0c3a94a0d9021c040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
